opt_in_rules:
  - indentation_width
  - array_init
  - attributes
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_body_length
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - collection_alignment
  - colon
  - compiler_protocol_init
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - custom_rules
  - cyclomatic_complexity
  - deployment_target
  - discarded_notification_center_observer
  - duplicate_enum_cases
  - duplicate_imports
  - dynamic_inline
  - empty_collection_literal
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_length
  - file_name
  - first_where
  - flatmap_over_map_reduce
  - for_where
  - force_cast
  - force_try
  - force_unwrapping
  - function_body_length
  # - function_default_parameter_at_end
  - function_parameter_count
  - generic_type_name
  - identical_operands
  - identifier_name
  - implicit_getter
  - implicitly_unwrapped_optional
  - is_disjoint
  - joined_default_parameter
  # - large_tuple
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_multiple
  - legacy_nsgeometry_functions
  - legacy_random
  - line_length
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - mark
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - multiple_closures_with_trailing_closure
  - nesting
  - nimble_operator
  - no_fallthrough_only
  - no_space_in_method_call
  - notification_center_detachment
  - nslocalizedstring_require_bundle
  - nsobject_prefer_isequal
  - object_literal
  - operator_usage_whitespace
  - operator_whitespace
  - pattern_matching_keywords
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - private_unit_test
  # - prohibited_super_call
  - protocol_property_accessors_order
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_boolean
  - reduce_into
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_void_return
  - required_enum_case
  - return_arrow_whitespace
  - shorthand_operator
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - statement_position
  - static_operator
  - syntactic_sugar
  - toggle_bool
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_enumerated
  - unused_optional_binding
  - unused_setter_value
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - void_return
  - weak_delegate
  - xct_specific_matcher
  - xctfail_message
  - yoda_condition

disabled_rules:
  - blanket_disable_command
  - superfluous_disable_command
  - opening_brace
  - todo
  - void_function_in_ternary
  - control_statement
  - private_over_fileprivate

# warning_threshold: 10

analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import

force_cast:
  error

force_try:
  severity: error

line_length: 140

function_body_length:
  warning: 70
  error: 100

file_length:
  warning: 600
  error: 700

type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 50
  allowed_symbols: [_]
  excluded:
    - IO

identifier_name:
  min_length:
    error: 3
  excluded:
    - id
    - URL
    - ru
    - to
    - vc
    - v
    - io
    - x
    - y

nesting:
  type_level: 3

trailing_comma:
  mandatory_comma: false

conditional_returns_on_newline:
  if_only: true

indentation_width: 4

reporter: "xcode"
